### ISSUE TITLE
Game Feature: Achievements

### ISSUE THREAD

**Issue by norshimself** [NorsHiden/42cursus-ft_transcendence#15]
# Description

The project will have an Achievement System, whenever a player collects or wins a reward, they will earn an achievement and it will be displayable on their profile page.

## Tasks

- [x] Achievement Entity.
- [x] Creating all Achievements Records.
- [x] Achievements endpoints.

## Achievements

[Account]
- [x] "Welcome Aboard!" - Logging in for the very first time.
- [x] "Social Pioneer" - Forging the First Friendship.
- [x] "Circle of Allies" - Gathering a diverse group of five friends.
- [x] "Master of Self-Presentation" - Knack for crafting a standout profile.

[Chat]
- [x] "DM Initiator" - Initiate direct message conversation.
- [x] "Quick Starter" - For sending 10 messages in the chat.
- [x] "Group Chat Starter" - Create and manage group chat room.
- [x] "Social Butterfly" - Participate in 10 different group chats.

[Game]
- [x] "Game On!" - Play your first game and join the fun.
- [x] "Victory Lap" - Win your very first game and savor the taste of success.
- [x] "Unbeatable Defender" - Win a game without allowing your opponent to score a single point.
- [x] "Pong Master" - Win 10 Pong matches.
