### ISSUE TITLE
Complete authentication process by Integrating Auth endpoints to frontend

### ISSUE THREAD

**Issue by Ereur** [NorsHiden/42cursus-ft_transcendence#32]
# Description

In this assignment, my primary focus is to Complete the authentication process by integrating these  API endpoints:

```md
[GET]    /api/auth/:provider/login    | trigger the Ooauth provider
[GET]    /api/auth/:provider/callback | get the code from the Ooauth provider
[GET]    /api/auth/is-authenticated   | return if the users is authenticated
[GET]    /api/auth/is-verified        | return if the users is verified
[GET]    /api/auth/logout             | revoke jwt of the authenticated users
[GET]    /api/users/me                | get the authenticated user
[GET]    /api/users/:id               | get user by id
[DELETE] /api/users/:id               | delete user by id
[PUT]    /api/users/:id               | update user by id

```
## Tasks

- [x] implement a router gard as a components that checks if user is-logged-in and verified and returns the requested router component otherwise returns redirect component to login page or /postlogin if it is not verified
- [x] adding a model to the login page component that gets the QueryPrams from  /login/?redirect=blabla and send it to the view-model that will generate the auth-link depends on the provider chosen (/api/auth/42/login/?redirect=bla or ....)
- [x] complete unverifed users profile by sending a post request to  /api/auth/complete-profile
- [x] sucssesfully logout the user
