### ISSUE TITLE
Design a Search component

### ISSUE THREAD

**Issue by Ereur** [NorsHiden/42cursus-ft_transcendence#35]
# Description

In this assignment, my primary focus is to style Search Component and implement the functionality and linking the serch with bakend.

this is the style im working on https://www.figma.com/proto/NhlxqpBaznMohJEdzwwyry/PONG-THE-GAME?type=design&node-id=945-1770&t=K9vMTTEGok3Zthjz-1&scaling=min-zoom&page-id=0%3A1&mode=design

i will try to achive this animation https://dribbble.com/shots/17399694-Search-Results-Animation  as discussed with @HxX2. using motion https://www.framer.com/motion/introduction/

## Tasks

- [x] add /search route
- [x] add functionality to send the input data to backend
- [x] style the component
- [x] add the right trnsitions and animations
