### ISSUE TITLE
Chat Feature

### ISSUE THREAD

**Issue by HxX2** [NorsHiden/42cursus-ft_transcendence#39]
# Description
Building chat feature with Channels and DM's support.

## Tasks

- [x] #47
- [x] Implement channel interactions (join, leave, invite)
- [x] Implement members interactions (kick, ban, mute, set as admin)
- [x] Implement Messages resource.
- [x] Implement gateway.
- [x] Add appropriate events.
