### ISSUE TITLE
Create User Settings Page for Updating Avatar, Banner, and Personal Information

### ISSUE THREAD

**Issue by Ereur** [NorsHiden/42cursus-ft_transcendence#56]
# Description
   create a new settings page where users can update their avatar, banner, and personal information.

## tasks

- [x] Setup settings layout for different screen sizes
- [x] styling
- [x] add 2fa modal
- [x] linking with backend
