### ISSUE TITLE
Game: front-end implementation

### ISSUE THREAD

**Issue by SsiCipher** [NorsHiden/42cursus-ft_transcendence#82]
# Game: front-end implementation

This issue serves as a tracker for the process of building the front-end part of the pong game.

## Tasks

- [x] create the basic layout of the game
- [x] create context to use socket + context helper function & hooks
- [x] create a socket with socket.io to connect to backend
