### ISSUE TITLE
Achievements: adding user achievements page to user profile

### ISSUE THREAD

**Issue by SsiCipher** [NorsHiden/42cursus-ft_transcendence#97]
# Achievements

Create user achievements page with reusable components to use in home page

## Tasks

- [x] Create achievements ENUM to use in back/front of the site
- [x] Create `Achievement` component to use in profile & homepage
- [x] Create user achievements page from UI with `Achievements` component
- [x] Connect page to backend

### Achievements Enum

```ts
enum AchievementType {
  WELCOME_ABOARD = 'WELCOME_ABOARD',
  SOCIAL_PIONEER = 'SOCIAL_PIONEER',
  CIRCLE_OF_ALLIES = 'CIRCLE_OF_ALLIES',
  DM_INITIATOR = 'DM_INITIATOR',
  QUICK_STARTER = 'QUICK_STARTER',
  GROUP_CHAT_STARTER = 'GROUP_CHAT_STARTER',
  SOCIAL_BUTTERFLY = 'SOCIAL_BUTTERFLY',
  GAME_ON = 'GAME_ON',
  VICTORY_LAP = 'VICTORY_LAP',
  UNBEATABLE_DEFENDER = 'UNBEATABLE_DEFENDER',
  PONG_MASTER = 'PONG_MASTER',
}
```

### Achievement Type

```ts
type AchievementType = {
  isClaimed: boolean;
  type: AchievementType;
  title: string;
  description: string;
};
```
