### ISSUE TITLE
Leaderboard: Implement leaderboard page

### ISSUE THREAD

**Issue by SsiCipher** [NorsHiden/42cursus-ft_transcendence#98]
# Leaderboard

## Tasks

- [x] Add new route for the leaderboard page
- [x] Create `LeaderboardCard` component
- [x] Create the page to use the `LeaderboardCard` component
- [x] Link the page with backend
